### ISSUE TITLE
v1.1.0 - Unknown MQTT command received armed

### ISSUE THREAD

**Issue by rg2k** [duanemck/ezviz.net#16]
Hi,

It seems the armed command no longer works with version 1.1.0. Still works with version 1.0.0.

1.1.0:
[2023-09-02 13:51:49][INFO ][ezviz_mqtt.MqttHandler             ]Received message via MQTT from [ezviz/cmnd/xxxx/armed] => ON
[2023-09-02 13:51:49][INFO ][ezviz_mqtt.MqttWorker              ]Unknown MQTT command received armed

Thanks

**Comment by duanemck** [comment]
Hi

I think this may be due to the new Home Assistant Autodiscovery features, the topic is slightly different.
But this shouldn't have broken if you're not using that, I'll dig into it on my side.

This is how I see it on my logs:

```
[INFO ][ezviz_mqtt.MqttHandler   ]Received message via MQTT from [ezviz/status/xxx/armed/set] => ON
[INFO ][ezviz_mqtt.MqttWorker    ]Setting [armed] for [xxx] to [ON]
[DEBUG][ezviz_mqtt.MqttHandler ]Publishing [ON] to [ezviz/status/xxx/armed]
[INFO ][ezviz_mqtt.MqttHandler   ]Received message via MQTT from [ezviz/status/xxx/armed/set] => OFF
[INFO ][ezviz_mqtt.MqttWorker    ]Setting [armed] for [xxx] to [OFF]
[DEBUG][ezviz_mqtt.MqttHandler ]Publishing [OFF] to [ezviz/status/xxx/armed]
```

**Comment by rg2k** [comment]
> Hi
> 
> I think this may be due to the new Home Assistant Autodiscovery features, the topic is slightly different. But this shouldn't have broken if you're not using that, I'll dig into it on my side.
> 
> This is how I see it on my logs:
> 
> ```
> [INFO ][ezviz_mqtt.MqttHandler   ]Received message via MQTT from [ezviz/status/xxx/armed/set] => ON
> [INFO ][ezviz_mqtt.MqttWorker    ]Setting [armed] for [xxx] to [ON]
> [DEBUG][ezviz_mqtt.MqttHandler ]Publishing [ON] to [ezviz/status/xxx/armed]
> [INFO ][ezviz_mqtt.MqttHandler   ]Received message via MQTT from [ezviz/status/xxx/armed/set] => OFF
> [INFO ][ezviz_mqtt.MqttWorker    ]Setting [armed] for [xxx] to [OFF]
> [DEBUG][ezviz_mqtt.MqttHandler ]Publishing [OFF] to [ezviz/status/xxx/armed]
> ```

Your response gave a clue - looks like you have added a /set after /armed. This is working with 1.1.0 now. Not sure if you need to update the wiki?
