### ISSUE TITLE
How to sponsor?

### ISSUE THREAD

**Issue by steelbrain** [duanemck/ezviz.net#5]
Hello!

Thanks for working on this initiative! Is there a way I could buy you a coffee or sponsor development of this project?

Thanks!

**Comment by duanemck** [comment]
Hello, thanks for the feedback. I setup a link you can use if you'd like: https://www.buymeacoffee.com/duanemck

Is there something specific you're looking to add to the project?

**Comment by steelbrain** [comment]
@duanemck Just gave some support. Thanks for setting it up!

I am using EZVIZ cameras through RTSP in my home setup with scrypted to add them to HomeKit. For privacy reasons, they are on a vlan/network that does not have internet access. While it's good for privacy, it also means that I lose the ability to control these cameras through anything other than their app with "LAN View".

I am looking for some help to continue the local connection work (I posted some of my own findings in https://github.com/BaQs/pyEzviz/issues/61#issuecomment-1505142712) so we can make a mqtt bridge for EZVIZ cameras that works over the local network so I can connect my cameras to the mqtt server in scrypted and use native motion detection and other events.

If someone can setup an MQTT bridge, I could also join the action and make an MQTT to onvif layer so end users can do pan/tilt/zoom from scrypted/homekit and other home nvr solutions without having to connect their cameras to the internet. I have verified that these functions are available through the app with lan view.

Does that sound like something that interests you? EZVIZ cameras are cheap and make home security accessible, I am sure many people would be able to benefit from your contributions :)

**Comment by duanemck** [comment]
Hi, apologies for the delay in getting back to you, I just haven't had much free time lately. I will have a closer look at your findings that you mentioned above and then see how I can help. And thanks again for the donation.

**Comment by duanemck** [comment]
I read through your comment (and comments on the other repo) again and I'm not sure I'm following.
This library controls the cameras through the Ezviz cloud API, it does not communicate directly with the camera. 
So I don't think it could be used for LAN only control of the devices. 

I'm not sure what an MQTT bridge would bridge between?

**Comment by duanemck** [comment]
Been thinking about this a bit more, I guess that because this app is .NET we may be able to extend it to integrate the Hikvision DLL into it, thereby creating an MQTT bridge to local control. Is that what you are after?

**Comment by steelbrain** [comment]
Hey! I ended up figuring out solution for my specific usecase https://github.com/steelbrain/alarm-server-mqtt -- We can call this case closed
