### ISSUE TITLE
MQTT Auto Discovery

### ISSUE THREAD

**Issue by rezzalex** [duanemck/ezviz.net#7]
Hello.

Would it be possible to able auto discovery topics, so that devices would be automatically created by Domoticz MQTT auto discovery feature ?

**Comment by duanemck** [comment]
I had started looking at auto discovery for Home Assistant but I hit some blockers in the architecture of the app so I put it on pause. It was a while ago so I'll need to remind myself what the issue was and tackle it again.

The most recent commits to `main` to have some of that code, it's just commented out for now.

**Comment by duanemck** [comment]
Does Domoticz use the same Auto Discovery protocol as HA?

**Comment by rezzalex** [comment]
I am pretty sure that the answer is yes : https://www.domoticz.com/wiki/MQTT#MQTT_Autodiscovery_Setup

**Comment by rezzalex** [comment]
Hello @duanemck ,

Any news on this MQTT autodiscovery feature ?

**Comment by duanemck** [comment]
Hi @rezzalex , I made some good progress on this back in May but then hit a snag where I couldn't figure out how to set the RTSP url in the auto-discovery message. Life then got in the way and I got distracted.

I'll see if I can pick it up again this weekend, I might be able to release a BETA version for you to try out based on where I am at the moment.

**Comment by rezzalex** [comment]
Thanks a lot !!!
That would be wonderful!

Don't bother too much regarding RTSP URL, in my case, Domoticz can only visualise MJPEG streams, not RTSP !

**Comment by duanemck** [comment]
I've pushed a preview version of the Docker image to
`duanemck/ezviz-mqtt:preview-auto-discover`
or
`duanemck/ezviz-mqtt-arm:preview-auto-discover` if you're using ARM

**Comment by rezzalex** [comment]
Thanks a lot,

I will test that ASAP:

How/where can I specify the auto-discovery prefix ?

**Comment by duanemck** [comment]
Hmm, I think that was a bit of an oversight on my part.
It's currently hardcoded as `homeassistant/{device_class}/{node_id}/{unique_id}/config` 
I see that Domoticz uses `homeassistant` by default but that it can be changed, I'll quickly add a config option.

`serviceLwtTopic` is the LWT topic for the whole ezvizmqtt app, so you can determine if it has crashed and is no longer monitoring the camera.

**Comment by rezzalex** [comment]
I think It would be great to have it as a modifiable option because I am already using the "_homeassistant_" prefix for ZwaveJsUI, and I think I will create a new and specific "MQTT auto discovrey hardware"  in DZ, just for having a specific  prefix as recommended here : 

![image](https://github.com/duanemck/ezviz.net/assets/35136439/b24a4945-5d2d-4c84-ae4a-1df5165cf22e)

**Comment by duanemck** [comment]
OK, pushed a new version to the same tag.
Under `mqtt`, there is a new property called `autodiscoverPrefix`, it will default to `homeassistant` but you can update it to match your config.

**Comment by rezzalex** [comment]
I have experienced an error 500 while updating the container with the new image and this while using docker-compose : 
![image](https://github.com/duanemck/ezviz.net/assets/35136439/45bd9e17-586e-4248-a768-675c49e2667b)

**Comment by rezzalex** [comment]
I have change the 2 port on host system, like this : 

> 
>  ports:
>       - "8086:8081/tcp"
>       - "8087:8082/tcp"

then I had tis error :  

![image](https://github.com/duanemck/ezviz.net/assets/35136439/0b432dfb-f1f9-4438-b9ca-5365b27463ec)

**Comment by duanemck** [comment]
Hmm, the only thing I suspect is that I'm sending a boolean value as ON/OFF as HomeAssistant supports that, maybe Domoticz doesn't. Luckily this is configurable: Under `json` there is a setting called `serializeBooleans`, it's set to 1 by default which means serialize to string. Change it to 0 which will cause it to just write true/false.

The other error about ports is related to a health check plugin that I haven't managed to get working in Docker. You can ignore the error for now but I will update it so it can be switched off in future.

**Comment by duanemck** [comment]
The other issue about "Not a directory" is caused by something going wrong when consuming the ezviz API, usually it's a response message with a property missing or something unexpected.

The app tries to log the response for further debugging, the location is configurable in `polling -> requestLogLocation`, normally `/dev/null` on Linux just writes the file nowhere, perhaps on the container this doesn't work. 

This error shouldn't stop the app from running, on the next API poll it will hopefully get a valid message back.

**Comment by duanemck** [comment]
That is awesome to hear! I'm going to run it for a bit on my local system and then I'll release it to the main tag. I'll also update the docs to reflect the Domoticz compatibility.

**Comment by rezzalex** [comment]
If you need help screen captures, feel free to ask

**Comment by rezzalex** [comment]
Hello,

Some feedback with the polling settings exeplicitely set to  5 for cam and 1 for alarms :
If my understanding is correct, all DZ devices are "Read only" status except the button "armed" which has an instantaneous effect when clicked.

Regqrding the alarm : I was expecting the DZ device called "Trigger Alarm" to be switched on cam motion detection  event when armed, and there is nothing. the message is OK in MQTT under "alarm/cam_name/" but nothing in Domoticz

Possible Enhancements : 

  - having the battery level  in a "general" "percentage" device in DZ
  - having the alarm immediately switched on when it occurred
  - having the last alarm picUrl in a "general" "text" device in DZ

**Comment by rezzalex** [comment]
Hello @duanemck ;

did you have time to review my last comments?

**Comment by rezzalex** [comment]
Also, 
When arming my cam from another source that ezviz mqtt, Domoticz seems to believe it has sent an (MQTT) command to all EzViz devices, even if this device is not supposed to be actionable, generating errors.

**Comment by duanemck** [comment]
Thanks very much for the feedback, I haven't had a chance to dig into the detail just yet.

**Comment by rezzalex** [comment]
Hello @duanemck ,

I saw you have created all the tickets and also release the MQTT auto discovery in stable version. Thank you for that.
Is there any change regarding the version I have already tested ?

**Comment by duanemck** [comment]
Hi, it's been a very busy few weeks with kids birthdays. Hoping I'll have some time soon to look into the issues your reported.
